[workspace]
channels = ["conda-forge"]
name = "fxi-profile-collection"
platforms = [{ platform = "linux-64", glibc = "2.17" }]
version = "2026.2.0"

[feature.profile.dependencies]
bluesky-base = ">=1.15.1,<2"
bluesky-queueserver = ">=0.0.25,<0.0.26"
# bluesky-widgets = ">=0.0.17,<0.0.18"
bluesky-queueserver-api = ">=0.0.13,<0.0.14"
bluesky-tiled-plugins = ">=2.0.9,<3"
bluesky-kafka = ">=0.10.0,<0.11"
ophyd = ">=1.11.2,<2"
ophyd-async = ">=0.13.7,<0.14"
databroker = "==2.0.0"
tiled-client = ">=0.2.18,<0.3"
nslsii = ">=0.11.9,<0.12"

matplotlib-base= ">=3.10"
networkx = ">=3.4.2,<4"
numpy = "*"
pyepics = "*"
python = ">=3.11"
semver = ">=3.0.4,<4"
qtpy = ">=2.4.3,<3"
pyqt = "<6"
reportlab = ">=4.4.1,<5"
cytoolz = ">=1.0.1,<2"
pypdf2 = ">=3.0.1,<4"
scipy = ">=1.16.1,<2"
tomopy = ">=1.14.4"
magicgui = ">=0.10.1,<0.11"
pystackreg = ">=0.2.8,<0.3"
hdf5-external-filter-plugins = ">=0.1.0,<0.2"
blosc-hdf5-plugin = ">=1.0.1,<2"
epicscorelibs = ">=7.0.7.99.1.1,<8"
pip = ">=26.0.1,<27"
pvapy = ">=5.6.0,<6"

[feature.profile.pypi-dependencies]
pvxslibs = ">=1.3.2, <2"
bluesky-widgets = { git = "https://github.com/bluesky/bluesky-widgets", branch = "master" }

[feature.profile.tasks]
nslsii-hotfix = "python -m pip install git+https://github.com/nsls-ii/nslsii --no-build-isolation --no-deps"
# nslsii =  { git = "https://github.com/nsls-ii/nslsii", branch="master"}

[feature.qs.dependencies]
bluesky-queueserver = ">=0.0.25,<0.0.26"
bluesky-httpserver = "*"

[feature.qs.tasks]
# This section needs some development work to understand the best way to
# thread the required configuration through both the task and files checked into
# the profile.  These will interact with the ansible roles for pushing out the
# systemd units
qs-backend = "start-re-manager --profile-dir=."
# TODO: pixi run start-re-manager --zmq-publish-console=ON --use-ipython-kernel=ON --startup-profile=collection --keep-re
qs-server = "uvicorn --host localhost --port 60610 bluesky_httpserver.server:app"

[feature.terminal.dependencies]
ipython = ">=9.5.0"
numpy = ">2"
pyqt = ">=5,<6"
qtconsole = ">=5.7.0,<6"

[feature.terminal.tasks]
start = "unset SESSION_MANAGER PYTHONPATH && MPLBACKEND=qtagg ipython --profile-dir=."
pvs = "ipython --profile-dir=. -c 'get_pv_types(); exit()'"

[environments]
terminal = {features=["profile", "terminal"], solve-group="profile"}
qs = {features=["profile", "qs"], solve-group="profile"}
